In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import sklearn as sk

In [4]:
kar = pd.read_excel("pakistan_aqi_weather.xlsx", sheet_name = "Karachi")

In [5]:
lah = pd.read_excel("pakistan_aqi_weather.xlsx", sheet_name = "Lahore")

In [6]:
kar.head()

,time,pm10,pm2_5,carbon_monoxide,nitrogen_dioxide,sulphur_dioxide,ozone,aerosol_optical_depth,dust,uv_index,...,cloud_cover_low,cloud_cover_mid,cloud_cover_high,wind_speed_10m,wind_direction_10m,wind_gusts_10m,shortwave_radiation,direct_radiation,diffuse_radiation,city
0,2022-01-01T00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,13,21.5,50,30.2,0,0,0,Karachi
1,2022-01-01T01:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,88,21.0,51,29.9,0,0,0,Karachi
2,2022-01-01T02:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,94,20.5,52,29.2,0,0,0,Karachi
3,2022-01-01T03:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,99,20.8,53,28.8,0,0,0,Karachi
4,2022-01-01T04:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,100,19.9,49,28.4,0,0,0,Karachi

In [7]:
lah.head()

,time,pm10,pm2_5,carbon_monoxide,nitrogen_dioxide,sulphur_dioxide,ozone,aerosol_optical_depth,dust,uv_index,...,cloud_cover_low,cloud_cover_mid,cloud_cover_high,wind_speed_10m,wind_direction_10m,wind_gusts_10m,shortwave_radiation,direct_radiation,diffuse_radiation,city
0,2022-01-01T00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,9,4.2,340,5.8,0,0,0,Lahore
1,2022-01-01T01:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,1,4.7,274,5.4,0,0,0,Lahore
2,2022-01-01T02:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,72,4.0,275,5.4,0,0,0,Lahore
3,2022-01-01T03:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,91,5.1,309,6.1,0,0,0,Lahore
4,2022-01-01T04:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,89,5.9,281,6.5,0,0,0,Lahore

In [8]:
kar.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38376 entries, 0 to 38375
Data columns (total 32 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   time                   38376 non-null  object
 1   pm10                   33211 non-null  float64
 2   pm2_5                  33211 non-null  float64
 3   carbon_monoxide        33211 non-null  float64
 4   nitrogen_dioxide       33211 non-null  float64
 5   sulphur_dioxide        33211 non-null  float64
 6   ozone                  33211 non-null  float64
 7   aerosol_optical_depth  33211 non-null  float64
 8   dust                   33211 non-null  float64
 9   uv_index               33211 non-null  float64
 10  uv_index_clear_sky     33211 non-null  float64
 11  ammonia                0 non-null      float64
 12  temperature_2m         38376 non-null  float64
 13  relative_humidity_2m   38376 non-null  int64
 14  dew_point_2m           38376 non-null  float64
 15  apparent_temperature   38376 non-null  float64
 16  precipitation          38376 non-null  float64
 17  rain                   38376 non-null  float64
 18  snowfall               38376 non-null  int64
 19  pressure_msl           38376 non-null  float64
 20  surface_pressure       38376 non-null  float64
 21  cloud_cover            38376 non-null  int64
 22  cloud_cover_low        38376 non-null  int64
 23  cloud_cover_mid        38376 non-null  int64
 24  cloud_cover_high       38376 non-null  int64
 25  wind_speed_10m         38376 non-null  float64
 26  wind_direction_10m     38376 non-null  int64
 27  wind_gusts_10m         38376 non-null  float64
 28  shortwave_radiation    38376 non-null  int64
 29  direct_radiation       38376 non-null  int64
 30  diffuse_radiation      38376 non-null  int64
 31  city                   38376 non-null  object
dtypes: float64(20), int64(10), object(2)
memory usage: 9.4+ MB

In [9]:
kar.drop(columns = ["ammonia"], inplace = True)

In [10]:
kar.dropna(subset = ["pm10","pm2_5","carbon_monoxide", "nitrogen_dioxide", "sulphur_dioxide", "ozone","aerosol_optical_depth", "dust", "uv_index", "uv_index_clear_sky"], inplace = True)

In [11]:
kar.info()

<class 'pandas.core.frame.DataFrame'>
Index: 33211 entries, 5165 to 38375
Data columns (total 31 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   time                   33211 non-null  object
 1   pm10                   33211 non-null  float64
 2   pm2_5                  33211 non-null  float64
 3   carbon_monoxide        33211 non-null  float64
 4   nitrogen_dioxide       33211 non-null  float64
 5   sulphur_dioxide        33211 non-null  float64
 6   ozone                  33211 non-null  float64
 7   aerosol_optical_depth  33211 non-null  float64
 8   dust                   33211 non-null  float64
 9   uv_index               33211 non-null  float64
 10  uv_index_clear_sky     33211 non-null  float64
 11  temperature_2m         33211 non-null  float64
 12  relative_humidity_2m   33211 non-null  int64
 13  dew_point_2m           33211 non-null  float64
 14  apparent_temperature   33211 non-null  float64
 15  precipitation          33211 non-null  float64
 16  rain                   33211 non-null  float64
 17  snowfall               33211 non-null  int64
 18  pressure_msl           33211 non-null  float64
 19  surface_pressure       33211 non-null  float64
 20  cloud_cover            33211 non-null  int64
 21  cloud_cover_low        33211 non-null  int64
 22  cloud_cover_mid        33211 non-null  int64
 23  cloud_cover_high       33211 non-null  int64
 24  wind_speed_10m         33211 non-null  float64
 25  wind_direction_10m     33211 non-null  int64
 26  wind_gusts_10m         33211 non-null  float64
 27  shortwave_radiation    33211 non-null  int64
 28  direct_radiation       33211 non-null  int64
 29  diffuse_radiation      33211 non-null  int64
 30  city                   33211 non-null  object
dtypes: float64(19), int64(10), object(2)
memory usage: 8.1+ MB

In [12]:
kar["time"] = pd.to_datetime(kar["time"])

In [13]:
 #### For LAHORE

In [14]:
lah.drop(columns = ["ammonia"], inplace = True)

In [15]:
lah.dropna(subset = ["pm10","pm2_5","carbon_monoxide", "nitrogen_dioxide", "sulphur_dioxide", "ozone","aerosol_optical_depth", "dust", "uv_index", "uv_index_clear_sky"], inplace = True)

In [16]:
lah["time"] = pd.to_datetime(lah["time"])

In [17]:
output_file = "pakistan_aqi_weather.xlsx"

with pd.ExcelWriter(output_file, engine="openpyxl") as writer:
    kar.to_excel(writer, sheet_name="Karachi", index=False)
    lah.to_excel(writer, sheet_name="Lahore", index=False)